artifacts_file: data/artifacts_isic.json # Path to the artifacts file for the ISIC dataset
batch_size: 12
ckpt_path: /YOUR/PATH/TO/CHECKPOINTS/vgg16_features.29.pth # Path to the checkpoint file for VGG16 at layer features.29 
data_paths:
- /YOUR/PATH/TO/DATASET # Path to the dataset, e.g., ISIC2019
dataset_name: isic # Name of the dataset
device: cuda
dir_precomputed_data: /YOUR/PATH/TO/PRECOMPUTED_DATA # Where to save precomputed data
img_size: 224
layer_name: features.29
model_name: vgg16
